version: '3'
services:
  nav-item:
    image: eooce/nav-item
    container_name: nav-item
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
      - DATABASE_URL=postgresql://user:password@host:5432/neondb?sslmode=require
    restart: unless-stopped
